### ISSUE TITLE
Related actions/services

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#32]
Support metadata specification for each doc so that you could add tags in the form of   SERVICE.ACTION [for instance category.add, categoryEntry.update], then, when generating the site, iterate over the metadata and index it so that if a person views the API documentation for services and actions for which a corresponding tag exists, a "see also" reference will appear. 

Presentation wise, it will also show this in search results (under the search results show “Related Topics:” in smaller font, and have all tags be clickable).

@jessp01 - please advise on how you think we should store this information in the schema.

**Comment by jessp01** [comment]
Hi @zoharbabin, 

My suggestion, as specified in the issue's description, was in relation to the manually written documentation [https://github.com/kaltura/developer-platform-docs], not the API docs auto generated from the XML schema. Therefore, no schema changes should be needed in order to implement it.

What I suggest is introducing a new field to the doc's metadata section [what Jekyll calls front matter], let's say we call it ```tags```. This will include a list of actions/services/enums/whatnot that is referred to in the doc. This can later be parsed by the LucyBot engine to form an index.

For example, https://github.com/kaltura/developer-platform-docs/blob/master/documentation/Secure_Control_and_Govern/Content-Categories-Management.md metadata can have a ```tags``` member with:
```
tags: category, categoryEntry, category.add, categoryEntry.add, categoryEntry.delete
```
and so on. So that, when someone searches for these terms, this doc will be suggested.

**Comment by zoharbabin** [comment]
I'm happy to add it if it's not much work... but I'm worried it won't be really used, and thus not worth the effort. As it will be a lot of maintenance work on the documentation side.

**Comment by jessp01** [comment]
Creating this mechanism will require some work though it's hardly rocket science. That said, yes, this will require continuous maintenance [and some discipline] as we add/update documents. I actually think it's a valuable feature but whether or not it's worth the effort is a question indeed. Maybe we can suspend this for now and revisit later on.

**Comment by bobby-brennan** [comment]
I implemented this by adding a `seeAlso` option to LucyBot.yml. [Here's a demo](http://18.237.78.121:3005/api-docs/service/session/action/start) that adds `session.end` and `session.get` to the `session.start` operation

I'm not sure putting these links in the search results makes sense - they'll often be duplicative with other search results, or won't be related to what you're searching for. Thoughts?

**Comment by jessp01** [comment]
Hi @bobby-brennan - I think this is more than enough for now and I agree with your comment about the search results.

**Comment by jessp01** [comment]
@bobby-brennan - can you provide an example of `seeAlso` usage in `ovp.LucyBot.yml`?

**Comment by bobby-brennan** [comment]
Here's an example:

```yaml
operationNavigation:
  - title: "Generate API Sessions"
    children:
      - title: "session"
        tag: "session"
        children:
          - operation: "session.start"
            seeAlso:
              - operation: "session.end"
```

**Comment by jessp01** [comment]
Hi @bobby-brennan,

Consider this block in ovp.LucyBot.yml:
```yml
  - title: "Secure, Control and Govern"
    children:
      - title: "Content Categories Management"
        markdownURL: /assets/documentation/Secure_Control_and_Govern/Content-Categories-Management.html
        path: "/Secure_Control_and_Govern/Content-Categories-Management.html"
        discussionURL: null
```

I tried:
```yml
  - title: "Secure, Control and Govern"
    children:
      - title: "Content Categories Management"
        markdownURL: /assets/documentation/Secure_Control_and_Govern/Content-Categories-Management.html
        path: "/Secure_Control_and_Govern/Content-Categories-Management.html"
        discussionURL: null
        seeAlso:
         - operation: "category.add"
         - operation: "categoryEntry.add"
         - operation: "categoryEntry.delete"
```
and also:
```
  - title: "Secure, Control and Govern"
    children:
      - title: "Content Categories Management"
        markdownURL: /assets/documentation/Secure_Control_and_Govern/Content-Categories-Management.html
        path: "/Secure_Control_and_Govern/Content-Categories-Management.html"
        discussionURL: null
        children:
         seeAlso:
          - operation: "category.add"
          - operation: "categoryEntry.add"
          - operation: "categoryEntry.delete"
```

When calling `lucybot build --prerender`, I get:
```
YAMLException: end of the stream or a document separator is expected at line 402, column 3:
         - operation: "categoryEntry.add"
      ^
    at generateError (/mnt/lb/developer-platform/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/mnt/lb/developer-platform/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/mnt/lb/developer-platform/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/mnt/lb/developer-platform/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/mnt/lb/developer-platform/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at getYAML (/mnt/lb/developer-platform/LucyBot.js:7:15)
    at Object.<anonymous> (/mnt/lb/developer-platform/LucyBot.js:12:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at readConfig (/usr/lib/node_modules/lucybot/build/build.js:66:16)
    at Command.module.exports (/usr/lib/node_modules/lucybot/build/build.js:508:16)
```

What am I missing here?:)
```
